// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Bookslider: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/zhb/Bookslider.vue')['default']
    'Bookslider copy': typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/zhb/Bookslider copy.vue')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Card: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/misc/Card.vue')['default']
    CatalogueSlider: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/zhb/CatalogueSlider.vue')['default']
    CollectionSlider: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/zhb/CollectionSlider.vue')['default']
    DarkToggle: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/demo/DarkToggle.vue')['default']
    FixedRatio: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/slider/FixedRatio.vue')['default']
    Image: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/image/Image.vue')['default']
    ImgBlur: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/image/ImgBlur.vue')['default']
    ImgPic: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/image/ImgPic.vue')['default']
    Loading: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/misc/Loading.vue')['default']
    PageSection: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/demo/PageSection.vue')['default']
    Row: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/misc/Row.vue')['default']
    SingleSelect: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/misc/SingleSelect.vue')['default']
    Slider: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/slider/Slider.vue')['default']
    SliderButton: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/slider/SliderButton.vue')['default']
    SliderFilter: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/slider/SliderFilter.vue')['default']
    SliderHeader: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/slider/SliderHeader.vue')['default']
    SliderIcon: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/slider/SliderIcon.vue')['default']
    SliderIconButton: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/slider/SliderIconButton.vue')['default']
    SliderRow: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/slider/SliderRow.vue')['default']
    SliderSelect: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/slider/SliderSelect.vue')['default']
    Snip: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/misc/Snip.vue')['default']
    ViewSelect: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/zhb/ViewSelect.vue')['default']
    ViewSlider: typeof import('C:/Users/spech/Documents/masp-git/vitesse-light/src/components/zhb/ViewSlider.vue')['default']
  }
}

export { }
